FROM node:18-alpine
WORKDIR /usr/src/app
RUN git clone https://github.com/darkrp03/Manual-Accounting-Frontend /app
RUN cd /Manual-Accounting-Frontend
RUN npm install
COPY .env .env
EXPOSE 8080
CMD [ "npm run dev" ]