FROM node:18 as build-stage
WORKDIR /usr/src/app
RUN git clone https://github.com/darkrp03/Manual-Accounting-Frontend .
RUN npm install
COPY .env .env
RUN npm run build

FROM nginx:stable as production-stage
COPY --from=build-stage /usr/src/app/dist /usr/share/nginx/html
COPY vue_app.conf /etc/nginx/conf.d/
EXPOSE 80
CMD [ "nginx", "-g", "daemon off;" ]