FROM node:18
WORKDIR /usr/src/app
RUN npm install -g http-server
RUN git clone https://github.com/darkrp03/Manual-Accounting-Frontend .
RUN npm install
COPY .env .env
RUN npm run build
CMD [ "http-server", "dist" ]